/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapV2FactorySol from './UniswapV2Factory.sol/index.js';
export type { uniswapV2FactorySol };
import type * as uniswapV2RouterSol from './UniswapV2Router.sol/index.js';
export type { uniswapV2RouterSol };
import type * as wethSol from './WETH.sol/index.js';
export type { wethSol };