/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IERC20Minimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20Minimal__factory>
getContractFactory(name: 'IUniswapV2Callee', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Callee__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'UniswapV2Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV2Factory__factory>
getContractFactory(name: 'UniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV2Pair__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Factory__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'UniswapV2Router02', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV2Router02__factory>
getContractFactory(name: 'WETH9', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WETH9__factory>
getContractFactory(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Factory__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'IUniswapV2Router02', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Router02__factory>
getContractFactory(name: 'BondingCurveV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BondingCurveV2__factory>
getContractFactory(name: 'IDevVesting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IDevVesting__factory>
getContractFactory(name: 'IFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFactory__factory>
getContractFactory(name: 'DevVestingV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DevVestingV2__factory>
getContractFactory(name: 'HypaToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HypaToken__factory>
getContractFactory(name: 'IBondingCurveV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBondingCurveV2__factory>
getContractFactory(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Factory__factory>
getContractFactory(name: 'IUniswapV2Router', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Router__factory>
getContractFactory(name: 'TokenFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenFactory__factory>
getContractFactory(name: 'IBondingCurve', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBondingCurve__factory>
getContractFactory(name: 'IHypaFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHypaFactory__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'PredictionMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionMarket__factory>

  getContractAt(name: 'IERC20Minimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20Minimal>
getContractAt(name: 'IUniswapV2Callee', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Callee>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'UniswapV2Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV2Factory>
getContractAt(name: 'UniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV2Pair>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'IUniswapV2Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Factory>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'UniswapV2Router02', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV2Router02>
getContractAt(name: 'WETH9', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WETH9>
getContractAt(name: 'IUniswapV2Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Factory>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'IUniswapV2Router02', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Router02>
getContractAt(name: 'BondingCurveV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BondingCurveV2>
getContractAt(name: 'IDevVesting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IDevVesting>
getContractAt(name: 'IFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFactory>
getContractAt(name: 'DevVestingV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DevVestingV2>
getContractAt(name: 'HypaToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HypaToken>
getContractAt(name: 'IBondingCurveV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBondingCurveV2>
getContractAt(name: 'IUniswapV2Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Factory>
getContractAt(name: 'IUniswapV2Router', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Router>
getContractAt(name: 'TokenFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenFactory>
getContractAt(name: 'IBondingCurve', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBondingCurve>
getContractAt(name: 'IHypaFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHypaFactory>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'PredictionMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionMarket>

  deployContract(name: 'IERC20Minimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Minimal>
deployContract(name: 'IUniswapV2Callee', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Callee>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'UniswapV2Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Factory>
deployContract(name: 'UniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Pair>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'UniswapV2Router02', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Router02>
deployContract(name: 'WETH9', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WETH9>
deployContract(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IUniswapV2Router02', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router02>
deployContract(name: 'BondingCurveV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BondingCurveV2>
deployContract(name: 'IDevVesting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDevVesting>
deployContract(name: 'IFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFactory>
deployContract(name: 'DevVestingV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DevVestingV2>
deployContract(name: 'HypaToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HypaToken>
deployContract(name: 'IBondingCurveV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBondingCurveV2>
deployContract(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Router', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router>
deployContract(name: 'TokenFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenFactory>
deployContract(name: 'IBondingCurve', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBondingCurve>
deployContract(name: 'IHypaFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHypaFactory>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'PredictionMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarket>

  deployContract(name: 'IERC20Minimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Minimal>
deployContract(name: 'IUniswapV2Callee', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Callee>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'UniswapV2Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Factory>
deployContract(name: 'UniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Pair>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'IUniswapV2Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'UniswapV2Router02', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV2Router02>
deployContract(name: 'WETH9', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WETH9>
deployContract(name: 'IUniswapV2Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IUniswapV2Router02', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router02>
deployContract(name: 'BondingCurveV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BondingCurveV2>
deployContract(name: 'IDevVesting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDevVesting>
deployContract(name: 'IFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFactory>
deployContract(name: 'DevVestingV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DevVestingV2>
deployContract(name: 'HypaToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HypaToken>
deployContract(name: 'IBondingCurveV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBondingCurveV2>
deployContract(name: 'IUniswapV2Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Router', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router>
deployContract(name: 'TokenFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenFactory>
deployContract(name: 'IBondingCurve', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBondingCurve>
deployContract(name: 'IHypaFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHypaFactory>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'PredictionMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarket>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  