/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBondingCurve, IBondingCurveInterface } from "../../../markets/PredictionMarket.sol/IBondingCurve.js";

  const _abi = [
  {
    "inputs": [],
    "name": "currentPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "graduated",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "realEthReserve",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IBondingCurve__factory {
    static readonly abi = _abi;
    static createInterface(): IBondingCurveInterface {
      return new Interface(_abi) as IBondingCurveInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBondingCurve {
      return new Contract(address, _abi, runner) as unknown as IBondingCurve;
    }
  }
  