/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IHypaFactory, IHypaFactoryInterface } from "../../../markets/PredictionMarket.sol/IHypaFactory.js";

  const _abi = [
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IHypaFactory__factory {
    static readonly abi = _abi;
    static createInterface(): IHypaFactoryInterface {
      return new Interface(_abi) as IHypaFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IHypaFactory {
      return new Contract(address, _abi, runner) as unknown as IHypaFactory;
    }
  }
  