/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IUniswapV2Pair, IUniswapV2PairInterface } from "../../../markets/PredictionMarket.sol/IUniswapV2Pair.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getReserves",
    "outputs": [
      {
        "internalType": "uint112",
        "name": "",
        "type": "uint112"
      },
      {
        "internalType": "uint112",
        "name": "",
        "type": "uint112"
      },
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "price0CumulativeLast",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "token0",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "token1",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IUniswapV2Pair__factory {
    static readonly abi = _abi;
    static createInterface(): IUniswapV2PairInterface {
      return new Interface(_abi) as IUniswapV2PairInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IUniswapV2Pair {
      return new Contract(address, _abi, runner) as unknown as IUniswapV2Pair;
    }
  }
  