/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface BondingCurveV2Interface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOM" | "CREATOR_TRADE_FEE_BPS" | "FEE_BPS" | "GRADUATION_ETH_TARGET" | "GRAD_FEE_BPS" | "TREASURY_TRADE_FEE_BPS" | "VIRT_ETH_INIT" | "VIRT_TOKEN_INIT" | "buy" | "claimCreatorFees" | "creator" | "currentPrice" | "devVesting" | "dexRouter" | "factory" | "graduated" | "graduationProgress" | "pendingCreatorFees" | "protocolTreasury" | "quoteBuy" | "quoteSell" | "realEthReserve" | "sell" | "setDevVesting" | "setDexRouter" | "setToken" | "token" | "virtualEthReserve" | "virtualTokenReserve"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Buy" | "CreatorFeesClaimed" | "Graduated" | "Sell"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOM', values?: undefined): string;
encodeFunctionData(functionFragment: 'CREATOR_TRADE_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'GRADUATION_ETH_TARGET', values?: undefined): string;
encodeFunctionData(functionFragment: 'GRAD_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'TREASURY_TRADE_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'VIRT_ETH_INIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'VIRT_TOKEN_INIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimCreatorFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'creator', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'devVesting', values?: undefined): string;
encodeFunctionData(functionFragment: 'dexRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'graduated', values?: undefined): string;
encodeFunctionData(functionFragment: 'graduationProgress', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingCreatorFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'protocolTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'quoteBuy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteSell', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'realEthReserve', values?: undefined): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDevVesting', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setDexRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'virtualEthReserve', values?: undefined): string;
encodeFunctionData(functionFragment: 'virtualTokenReserve', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CREATOR_TRADE_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GRADUATION_ETH_TARGET', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GRAD_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TREASURY_TRADE_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VIRT_ETH_INIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VIRT_TOKEN_INIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimCreatorFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'devVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dexRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'graduated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'graduationProgress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingCreatorFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'realEthReserve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDevVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDexRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'virtualEthReserve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'virtualTokenReserve', data: BytesLike): Result;
  }

  
    export namespace BuyEvent {
      export type InputTuple = [buyer: AddressLike, ethIn: BigNumberish, tokensOut: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [buyer: string, ethIn: bigint, tokensOut: bigint, fee: bigint];
      export interface OutputObject {buyer: string, ethIn: bigint, tokensOut: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreatorFeesClaimedEvent {
      export type InputTuple = [creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [creator: string, amount: bigint];
      export interface OutputObject {creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GraduatedEvent {
      export type InputTuple = [ethToLp: BigNumberish, ethToTreasury: BigNumberish, tokensToLp: BigNumberish];
      export type OutputTuple = [ethToLp: bigint, ethToTreasury: bigint, tokensToLp: bigint];
      export interface OutputObject {ethToLp: bigint, ethToTreasury: bigint, tokensToLp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SellEvent {
      export type InputTuple = [seller: AddressLike, tokensIn: BigNumberish, ethOut: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [seller: string, tokensIn: bigint, ethOut: bigint, fee: bigint];
      export interface OutputObject {seller: string, tokensIn: bigint, ethOut: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BondingCurveV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): BondingCurveV2;
    waitForDeployment(): Promise<this>;

    interface: BondingCurveV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOM: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CREATOR_TRADE_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    GRADUATION_ETH_TARGET: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    GRAD_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TREASURY_TRADE_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VIRT_ETH_INIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VIRT_TOKEN_INIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [minTokensOut: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    claimCreatorFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    creator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    currentPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    devVesting: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    dexRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    graduated: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    graduationProgress: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingCreatorFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    protocolTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quoteBuy: TypedContractMethod<
      [ethIn: BigNumberish, ],
      [[bigint, bigint] & {tokensOut: bigint, fee: bigint }],
      'view'
    >
    

    
    quoteSell: TypedContractMethod<
      [tokensIn: BigNumberish, ],
      [[bigint, bigint] & {ethOut: bigint, fee: bigint }],
      'view'
    >
    

    
    realEthReserve: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    sell: TypedContractMethod<
      [tokensIn: BigNumberish, minEthOut: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDevVesting: TypedContractMethod<
      [vesting_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDexRouter: TypedContractMethod<
      [router_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setToken: TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    virtualEthReserve: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    virtualTokenReserve: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOM'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CREATOR_TRADE_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'GRADUATION_ETH_TARGET'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'GRAD_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TREASURY_TRADE_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VIRT_ETH_INIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VIRT_TOKEN_INIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [minTokensOut: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'claimCreatorFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'currentPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'devVesting'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'dexRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'graduated'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'graduationProgress'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingCreatorFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'protocolTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteBuy'): TypedContractMethod<
      [ethIn: BigNumberish, ],
      [[bigint, bigint] & {tokensOut: bigint, fee: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'quoteSell'): TypedContractMethod<
      [tokensIn: BigNumberish, ],
      [[bigint, bigint] & {ethOut: bigint, fee: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'realEthReserve'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [tokensIn: BigNumberish, minEthOut: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDevVesting'): TypedContractMethod<
      [vesting_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDexRouter'): TypedContractMethod<
      [router_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setToken'): TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'virtualEthReserve'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'virtualTokenReserve'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Buy'): TypedContractEvent<BuyEvent.InputTuple, BuyEvent.OutputTuple, BuyEvent.OutputObject>;
getEvent(key: 'CreatorFeesClaimed'): TypedContractEvent<CreatorFeesClaimedEvent.InputTuple, CreatorFeesClaimedEvent.OutputTuple, CreatorFeesClaimedEvent.OutputObject>;
getEvent(key: 'Graduated'): TypedContractEvent<GraduatedEvent.InputTuple, GraduatedEvent.OutputTuple, GraduatedEvent.OutputObject>;
getEvent(key: 'Sell'): TypedContractEvent<SellEvent.InputTuple, SellEvent.OutputTuple, SellEvent.OutputObject>;

    filters: {
      
      'Buy(address,uint256,uint256,uint256)': TypedContractEvent<BuyEvent.InputTuple, BuyEvent.OutputTuple, BuyEvent.OutputObject>;
      Buy: TypedContractEvent<BuyEvent.InputTuple, BuyEvent.OutputTuple, BuyEvent.OutputObject>;
    

      'CreatorFeesClaimed(address,uint256)': TypedContractEvent<CreatorFeesClaimedEvent.InputTuple, CreatorFeesClaimedEvent.OutputTuple, CreatorFeesClaimedEvent.OutputObject>;
      CreatorFeesClaimed: TypedContractEvent<CreatorFeesClaimedEvent.InputTuple, CreatorFeesClaimedEvent.OutputTuple, CreatorFeesClaimedEvent.OutputObject>;
    

      'Graduated(uint256,uint256,uint256)': TypedContractEvent<GraduatedEvent.InputTuple, GraduatedEvent.OutputTuple, GraduatedEvent.OutputObject>;
      Graduated: TypedContractEvent<GraduatedEvent.InputTuple, GraduatedEvent.OutputTuple, GraduatedEvent.OutputObject>;
    

      'Sell(address,uint256,uint256,uint256)': TypedContractEvent<SellEvent.InputTuple, SellEvent.OutputTuple, SellEvent.OutputObject>;
      Sell: TypedContractEvent<SellEvent.InputTuple, SellEvent.OutputTuple, SellEvent.OutputObject>;
    
    };
  }