/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as uniswapV2FactorySol from './UniswapV2Factory.sol/index.js';
export * as uniswapV2RouterSol from './UniswapV2Router.sol/index.js';
export * as wethSol from './WETH.sol/index.js';