/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Minimal } from './IERC20Minimal.js';
export type { IUniswapV2Callee } from './IUniswapV2Callee.js';
export type { IUniswapV2Pair } from './IUniswapV2Pair.js';
export type { UniswapV2Factory } from './UniswapV2Factory.js';
export type { UniswapV2Pair } from './UniswapV2Pair.js';