/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace TokenFactory {
      
    export type LaunchParamsStruct = {name: string, symbol: string, ipfsHash: string, devAllocationPct: BigNumberish, vestingMonths: BigNumberish, launchMarketBitmask: BigNumberish, ethTarget: BigNumberish, ethTargetHours: BigNumberish, launchPriceMultX10: BigNumberish, launchPriceMultHours: BigNumberish, gradMarketBitmask: BigNumberish, gradMcapMultX10: BigNumberish, gradMcapMultDays: BigNumberish, gradPriceMultX10: BigNumberish, gradPriceMultDays: BigNumberish, gradMinLiquidity: BigNumberish, gradLiquidityDays: BigNumberish}

    export type LaunchParamsStructOutput = [name: string, symbol: string, ipfsHash: string, devAllocationPct: bigint, vestingMonths: bigint, launchMarketBitmask: bigint, ethTarget: bigint, ethTargetHours: bigint, launchPriceMultX10: bigint, launchPriceMultHours: bigint, gradMarketBitmask: bigint, gradMcapMultX10: bigint, gradMcapMultDays: bigint, gradPriceMultX10: bigint, gradPriceMultDays: bigint, gradMinLiquidity: bigint, gradLiquidityDays: bigint] & {name: string, symbol: string, ipfsHash: string, devAllocationPct: bigint, vestingMonths: bigint, launchMarketBitmask: bigint, ethTarget: bigint, ethTargetHours: bigint, launchPriceMultX10: bigint, launchPriceMultHours: bigint, gradMarketBitmask: bigint, gradMcapMultX10: bigint, gradMcapMultDays: bigint, gradPriceMultX10: bigint, gradPriceMultDays: bigint, gradMinLiquidity: bigint, gradLiquidityDays: bigint }
  
    }

  export interface TokenFactoryInterface extends Interface {
    getFunction(nameOrSignature: "allTokens" | "devTokens" | "dexRouter" | "getDevTokens" | "getPool" | "graduationEthTarget" | "launch" | "launchFeeWei" | "launches" | "owner" | "predictionMarket" | "protocolTreasury" | "seedLiquidity" | "seedLiquidityManual" | "setDexRouter" | "setGraduationTarget" | "setPredictionMarket" | "setTreasury" | "setVirtualEthInit" | "totalLaunched" | "transferOwnership" | "virtualEthInit"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Graduated" | "Launched" | "LiquiditySeeded" | "RouterUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'allTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'devTokens', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'dexRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDevTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'graduationEthTarget', values?: undefined): string;
encodeFunctionData(functionFragment: 'launch', values: [TokenFactory.LaunchParamsStruct]): string;
encodeFunctionData(functionFragment: 'launchFeeWei', values?: undefined): string;
encodeFunctionData(functionFragment: 'launches', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'predictionMarket', values?: undefined): string;
encodeFunctionData(functionFragment: 'protocolTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'seedLiquidity', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'seedLiquidityManual', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setDexRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setGraduationTarget', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPredictionMarket', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setVirtualEthInit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalLaunched', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'virtualEthInit', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'allTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'devTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dexRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDevTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'graduationEthTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'launch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'launchFeeWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'launches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictionMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seedLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seedLiquidityManual', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDexRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGraduationTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPredictionMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVirtualEthInit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLaunched', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'virtualEthInit', data: BytesLike): Result;
  }

  
    export namespace GraduatedEvent {
      export type InputTuple = [token: AddressLike, pool: AddressLike];
      export type OutputTuple = [token: string, pool: string];
      export interface OutputObject {token: string, pool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LaunchedEvent {
      export type InputTuple = [token: AddressLike, curve: AddressLike, dev: AddressLike, name: string, symbol: string];
      export type OutputTuple = [token: string, curve: string, dev: string, name: string, symbol: string];
      export interface OutputObject {token: string, curve: string, dev: string, name: string, symbol: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquiditySeededEvent {
      export type InputTuple = [token: AddressLike, eth: BigNumberish, tokens: BigNumberish];
      export type OutputTuple = [token: string, eth: bigint, tokens: bigint];
      export interface OutputObject {token: string, eth: bigint, tokens: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RouterUpdatedEvent {
      export type InputTuple = [router: AddressLike];
      export type OutputTuple = [router: string];
      export interface OutputObject {router: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenFactory;
    waitForDeployment(): Promise<this>;

    interface: TokenFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allTokens: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    devTokens: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    dexRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getDevTokens: TypedContractMethod<
      [dev_: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getPool: TypedContractMethod<
      [token_: AddressLike, ],
      [string],
      'view'
    >
    

    
    graduationEthTarget: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    launch: TypedContractMethod<
      [p: TokenFactory.LaunchParamsStruct, ],
      [[string, string, string] & {token_: string, curve_: string, vesting_: string }],
      'payable'
    >
    

    
    launchFeeWei: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    launches: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, string, string, string, bigint, boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {token: string, bondingCurve: string, devVesting: string, pool: string, dev: string, launchedAt: bigint, graduated: boolean, gradMarketBitmask: bigint, gradMcapMultX10: bigint, gradMcapMultDays: bigint, gradPriceMultX10: bigint, gradPriceMultDays: bigint, gradMinLiquidity: bigint, gradLiquidityDays: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    predictionMarket: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    protocolTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    seedLiquidity: TypedContractMethod<
      [token_: AddressLike, tokenAmount: BigNumberish, ethAmount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    seedLiquidityManual: TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDexRouter: TypedContractMethod<
      [r: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setGraduationTarget: TypedContractMethod<
      [t: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPredictionMarket: TypedContractMethod<
      [p: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [t: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setVirtualEthInit: TypedContractMethod<
      [v: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalLaunched: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [n: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    virtualEthInit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allTokens'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'devTokens'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'dexRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDevTokens'): TypedContractMethod<
      [dev_: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPool'): TypedContractMethod<
      [token_: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'graduationEthTarget'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'launch'): TypedContractMethod<
      [p: TokenFactory.LaunchParamsStruct, ],
      [[string, string, string] & {token_: string, curve_: string, vesting_: string }],
      'payable'
    >;
getFunction(nameOrSignature: 'launchFeeWei'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'launches'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, string, string, string, bigint, boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {token: string, bondingCurve: string, devVesting: string, pool: string, dev: string, launchedAt: bigint, graduated: boolean, gradMarketBitmask: bigint, gradMcapMultX10: bigint, gradMcapMultDays: bigint, gradPriceMultX10: bigint, gradPriceMultDays: bigint, gradMinLiquidity: bigint, gradLiquidityDays: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictionMarket'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'protocolTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'seedLiquidity'): TypedContractMethod<
      [token_: AddressLike, tokenAmount: BigNumberish, ethAmount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'seedLiquidityManual'): TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDexRouter'): TypedContractMethod<
      [r: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGraduationTarget'): TypedContractMethod<
      [t: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPredictionMarket'): TypedContractMethod<
      [p: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [t: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVirtualEthInit'): TypedContractMethod<
      [v: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalLaunched'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [n: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'virtualEthInit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Graduated'): TypedContractEvent<GraduatedEvent.InputTuple, GraduatedEvent.OutputTuple, GraduatedEvent.OutputObject>;
getEvent(key: 'Launched'): TypedContractEvent<LaunchedEvent.InputTuple, LaunchedEvent.OutputTuple, LaunchedEvent.OutputObject>;
getEvent(key: 'LiquiditySeeded'): TypedContractEvent<LiquiditySeededEvent.InputTuple, LiquiditySeededEvent.OutputTuple, LiquiditySeededEvent.OutputObject>;
getEvent(key: 'RouterUpdated'): TypedContractEvent<RouterUpdatedEvent.InputTuple, RouterUpdatedEvent.OutputTuple, RouterUpdatedEvent.OutputObject>;

    filters: {
      
      'Graduated(address,address)': TypedContractEvent<GraduatedEvent.InputTuple, GraduatedEvent.OutputTuple, GraduatedEvent.OutputObject>;
      Graduated: TypedContractEvent<GraduatedEvent.InputTuple, GraduatedEvent.OutputTuple, GraduatedEvent.OutputObject>;
    

      'Launched(address,address,address,string,string)': TypedContractEvent<LaunchedEvent.InputTuple, LaunchedEvent.OutputTuple, LaunchedEvent.OutputObject>;
      Launched: TypedContractEvent<LaunchedEvent.InputTuple, LaunchedEvent.OutputTuple, LaunchedEvent.OutputObject>;
    

      'LiquiditySeeded(address,uint256,uint256)': TypedContractEvent<LiquiditySeededEvent.InputTuple, LiquiditySeededEvent.OutputTuple, LiquiditySeededEvent.OutputObject>;
      LiquiditySeeded: TypedContractEvent<LiquiditySeededEvent.InputTuple, LiquiditySeededEvent.OutputTuple, LiquiditySeededEvent.OutputObject>;
    

      'RouterUpdated(address)': TypedContractEvent<RouterUpdatedEvent.InputTuple, RouterUpdatedEvent.OutputTuple, RouterUpdatedEvent.OutputObject>;
      RouterUpdated: TypedContractEvent<RouterUpdatedEvent.InputTuple, RouterUpdatedEvent.OutputTuple, RouterUpdatedEvent.OutputObject>;
    
    };
  }