/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface DevVestingV2Interface extends Interface {
    getFunction(nameOrSignature: "MAX_DURATION" | "MIN_DURATION" | "bondingCurve" | "claim" | "claimable" | "claimed" | "dev" | "factory" | "setToken" | "startVesting" | "token" | "totalAmount" | "vestingDuration" | "vestingStart" | "vestingStarted"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "VestingStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'bondingCurve', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimable', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimed', values?: undefined): string;
encodeFunctionData(functionFragment: 'dev', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'setToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'startVesting', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vestingDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'vestingStart', values?: undefined): string;
encodeFunctionData(functionFragment: 'vestingStarted', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bondingCurve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dev', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startVesting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vestingDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vestingStart', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vestingStarted', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [dev: AddressLike, amount: BigNumberish];
      export type OutputTuple = [dev: string, amount: bigint];
      export interface OutputObject {dev: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VestingStartedEvent {
      export type InputTuple = [startTime: BigNumberish, total: BigNumberish];
      export type OutputTuple = [startTime: bigint, total: bigint];
      export interface OutputObject {startTime: bigint, total: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DevVestingV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): DevVestingV2;
    waitForDeployment(): Promise<this>;

    interface: DevVestingV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bondingCurve: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimable: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    dev: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setToken: TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    startVesting: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vestingDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vestingStart: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vestingStarted: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bondingCurve'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimable'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dev'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setToken'): TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startVesting'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vestingDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vestingStart'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vestingStarted'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'VestingStarted'): TypedContractEvent<VestingStartedEvent.InputTuple, VestingStartedEvent.OutputTuple, VestingStartedEvent.OutputObject>;

    filters: {
      
      'Claimed(address,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'VestingStarted(uint256,uint256)': TypedContractEvent<VestingStartedEvent.InputTuple, VestingStartedEvent.OutputTuple, VestingStartedEvent.OutputObject>;
      VestingStarted: TypedContractEvent<VestingStartedEvent.InputTuple, VestingStartedEvent.OutputTuple, VestingStartedEvent.OutputObject>;
    
    };
  }