/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IDevVesting, IDevVestingInterface } from "../../../launchpad/BondingCurve.sol/IDevVesting.js";

  const _abi = [
  {
    "inputs": [],
    "name": "startVesting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IDevVesting__factory {
    static readonly abi = _abi;
    static createInterface(): IDevVestingInterface {
      return new Interface(_abi) as IDevVestingInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IDevVesting {
      return new Contract(address, _abi, runner) as unknown as IDevVesting;
    }
  }
  