/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFactory, IFactoryInterface } from "../../../launchpad/BondingCurve.sol/IFactory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "tokenAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "ethAmount",
        "type": "uint256"
      }
    ],
    "name": "seedLiquidity",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IFactory__factory {
    static readonly abi = _abi;
    static createInterface(): IFactoryInterface {
      return new Interface(_abi) as IFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFactory {
      return new Contract(address, _abi, runner) as unknown as IFactory;
    }
  }
  