/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { IUniswapV2Factory } from './IUniswapV2Factory.js';
export type { IUniswapV2Pair } from './IUniswapV2Pair.js';
export type { IWETH } from './IWETH.js';
export type { UniswapV2Router02 } from './UniswapV2Router02.js';