/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IUniswapV2PairInterface extends Interface {
    getFunction(nameOrSignature: "burn" | "getReserves" | "mint" | "price0CumulativeLast" | "price1CumulativeLast" | "swap" | "token0"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'burn', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'price0CumulativeLast', values?: undefined): string;
encodeFunctionData(functionFragment: 'price1CumulativeLast', values?: undefined): string;
encodeFunctionData(functionFragment: 'swap', values: [BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'token0', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'price0CumulativeLast', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'price1CumulativeLast', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token0', data: BytesLike): Result;
  }

  

  export interface IUniswapV2Pair extends BaseContract {
    
    connect(runner?: ContractRunner | null): IUniswapV2Pair;
    waitForDeployment(): Promise<this>;

    interface: IUniswapV2PairInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    burn: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint]],
      'nonpayable'
    >
    

    
    getReserves: TypedContractMethod<
      [],
      [[bigint, bigint, bigint]],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    price0CumulativeLast: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    price1CumulativeLast: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swap: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, arg3: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    token0: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getReserves'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'price0CumulativeLast'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'price1CumulativeLast'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, arg3: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token0'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }