/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace PredictionMarket {
      
    export type MarketStruct = {token: AddressLike, curve: AddressLike, pool: AddressLike, marketType: BigNumberish, status: BigNumberish, deadline: BigNumberish, ethTarget: BigNumberish, multiplierX10: BigNumberish, strikePrice: BigNumberish, graduationMcap: BigNumberish, graduationPrice: BigNumberish, minLiquidity: BigNumberish, cumulativeAtStart: BigNumberish, timestampAtStart: BigNumberish, winningBucket: BigNumberish, description: string, outcome: boolean, resolutionTime: BigNumberish}

    export type MarketStructOutput = [token: string, curve: string, pool: string, marketType: bigint, status: bigint, deadline: bigint, ethTarget: bigint, multiplierX10: bigint, strikePrice: bigint, graduationMcap: bigint, graduationPrice: bigint, minLiquidity: bigint, cumulativeAtStart: bigint, timestampAtStart: bigint, winningBucket: bigint, description: string, outcome: boolean, resolutionTime: bigint] & {token: string, curve: string, pool: string, marketType: bigint, status: bigint, deadline: bigint, ethTarget: bigint, multiplierX10: bigint, strikePrice: bigint, graduationMcap: bigint, graduationPrice: bigint, minLiquidity: bigint, cumulativeAtStart: bigint, timestampAtStart: bigint, winningBucket: bigint, description: string, outcome: boolean, resolutionTime: bigint }
  
    }

  export interface PredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOM" | "ENTRY_FEE_BPS" | "claim" | "claimRange" | "claimed" | "createCustomMarket" | "createEthTargetMarket" | "createGraduationMarkets" | "createLaunchMarkets" | "createPostLiquidityMarket" | "createPostMcapMultMarket" | "createPostPriceMultMarket" | "createPriceMultMarket" | "factory" | "getMarket" | "getTokenMarkets" | "getUserStakes" | "marketCount" | "markets" | "noPool" | "noStakes" | "pendingWinnings" | "protocolTreasury" | "rangePool" | "rangeStakes" | "refund" | "resolve" | "resolveCustom" | "resolveGradMarkets" | "resolveRange" | "stake" | "stakeRange" | "tokenMarkets" | "yesPool" | "yesStakes"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarketCancelled" | "MarketCreated" | "MarketResolved" | "StakePlaced" | "WinningsClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOM', values?: undefined): string;
encodeFunctionData(functionFragment: 'ENTRY_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRange', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCustomMarket', values: [AddressLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEthTargetMarket', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createGraduationMarkets', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createLaunchMarkets', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPostLiquidityMarket', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPostMcapMultMarket', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPostPriceMultMarket', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPriceMultMarket', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTokenMarkets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserStakes', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'markets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'noPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'noStakes', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'pendingWinnings', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'protocolTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'rangePool', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rangeStakes', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolve', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveCustom', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'resolveGradMarkets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'resolveRange', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'stakeRange', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenMarkets', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'yesPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'yesStakes', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ENTRY_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCustomMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEthTargetMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createGraduationMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLaunchMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPostLiquidityMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPostMcapMultMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPostPriceMultMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPriceMultMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserStakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'noPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'noStakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWinnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rangePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rangeStakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveCustom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveGradMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yesPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yesStakes', data: BytesLike): Result;
  }

  
    export namespace MarketCancelledEvent {
      export type InputTuple = [id: BigNumberish];
      export type OutputTuple = [id: bigint];
      export interface OutputObject {id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatedEvent {
      export type InputTuple = [id: BigNumberish, token: AddressLike, mtype: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, token: string, mtype: bigint, deadline: bigint];
      export interface OutputObject {id: bigint, token: string, mtype: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [id: BigNumberish, outcome: boolean, bucket: BigNumberish];
      export type OutputTuple = [id: bigint, outcome: boolean, bucket: bigint];
      export interface OutputObject {id: bigint, outcome: boolean, bucket: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakePlacedEvent {
      export type InputTuple = [id: BigNumberish, staker: AddressLike, side: BigNumberish, net: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [id: bigint, staker: string, side: bigint, net: bigint, fee: bigint];
      export interface OutputObject {id: bigint, staker: string, side: bigint, net: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinningsClaimedEvent {
      export type InputTuple = [id: BigNumberish, winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, winner: string, amount: bigint];
      export interface OutputObject {id: bigint, winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOM: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ENTRY_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimRange: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createCustomMarket: TypedContractMethod<
      [token_: AddressLike, description_: string, deadlineHours_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    createEthTargetMarket: TypedContractMethod<
      [token_: AddressLike, curve_: AddressLike, ethTarget_: BigNumberish, deadlineHours_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    createGraduationMarkets: TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, gradMcap_: BigNumberish, gradPrice_: BigNumberish, marketBitmask_: BigNumberish, mcapMultX10_: BigNumberish, mcapMultDays_: BigNumberish, priceMultX10_: BigNumberish, priceMultDays_: BigNumberish, minLiquidity_: BigNumberish, liquidityDays_: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    createLaunchMarkets: TypedContractMethod<
      [token_: AddressLike, curve_: AddressLike, marketBitmask_: BigNumberish, ethTarget_: BigNumberish, ethTargetHours_: BigNumberish, priceMultX10_: BigNumberish, priceMultHours_: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >
    

    
    createPostLiquidityMarket: TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, minLiq_: BigNumberish, deadlineDays_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    createPostMcapMultMarket: TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, gradMcap_: BigNumberish, multX10_: BigNumberish, deadlineDays_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    createPostPriceMultMarket: TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, gradPrice_: BigNumberish, multX10_: BigNumberish, deadlineDays_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    createPriceMultMarket: TypedContractMethod<
      [token_: AddressLike, curve_: AddressLike, multX10_: BigNumberish, deadlineHours_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getMarket: TypedContractMethod<
      [id: BigNumberish, ],
      [PredictionMarket.MarketStructOutput],
      'view'
    >
    

    
    getTokenMarkets: TypedContractMethod<
      [t: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getUserStakes: TypedContractMethod<
      [id: BigNumberish, u: AddressLike, ],
      [[bigint, bigint] & {y: bigint, n: bigint }],
      'view'
    >
    

    
    marketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    markets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string, boolean, bigint] & {token: string, curve: string, pool: string, marketType: bigint, status: bigint, deadline: bigint, ethTarget: bigint, multiplierX10: bigint, strikePrice: bigint, graduationMcap: bigint, graduationPrice: bigint, minLiquidity: bigint, cumulativeAtStart: bigint, timestampAtStart: bigint, winningBucket: bigint, description: string, outcome: boolean, resolutionTime: bigint }],
      'view'
    >
    

    
    noPool: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    noStakes: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    pendingWinnings: TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    protocolTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rangePool: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    rangeStakes: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolve: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveCustom: TypedContractMethod<
      [marketId: BigNumberish, outcome: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    resolveGradMarkets: TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveRange: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [marketId: BigNumberish, side: boolean, ],
      [void],
      'payable'
    >
    

    
    stakeRange: TypedContractMethod<
      [marketId: BigNumberish, bucket: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    tokenMarkets: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    yesPool: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    yesStakes: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOM'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ENTRY_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimRange'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createCustomMarket'): TypedContractMethod<
      [token_: AddressLike, description_: string, deadlineHours_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEthTargetMarket'): TypedContractMethod<
      [token_: AddressLike, curve_: AddressLike, ethTarget_: BigNumberish, deadlineHours_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createGraduationMarkets'): TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, gradMcap_: BigNumberish, gradPrice_: BigNumberish, marketBitmask_: BigNumberish, mcapMultX10_: BigNumberish, mcapMultDays_: BigNumberish, priceMultX10_: BigNumberish, priceMultDays_: BigNumberish, minLiquidity_: BigNumberish, liquidityDays_: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createLaunchMarkets'): TypedContractMethod<
      [token_: AddressLike, curve_: AddressLike, marketBitmask_: BigNumberish, ethTarget_: BigNumberish, ethTargetHours_: BigNumberish, priceMultX10_: BigNumberish, priceMultHours_: BigNumberish, ],
      [bigint[]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPostLiquidityMarket'): TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, minLiq_: BigNumberish, deadlineDays_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPostMcapMultMarket'): TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, gradMcap_: BigNumberish, multX10_: BigNumberish, deadlineDays_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPostPriceMultMarket'): TypedContractMethod<
      [token_: AddressLike, pool_: AddressLike, gradPrice_: BigNumberish, multX10_: BigNumberish, deadlineDays_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPriceMultMarket'): TypedContractMethod<
      [token_: AddressLike, curve_: AddressLike, multX10_: BigNumberish, deadlineHours_: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [id: BigNumberish, ],
      [PredictionMarket.MarketStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMarkets'): TypedContractMethod<
      [t: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserStakes'): TypedContractMethod<
      [id: BigNumberish, u: AddressLike, ],
      [[bigint, bigint] & {y: bigint, n: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'marketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'markets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string, boolean, bigint] & {token: string, curve: string, pool: string, marketType: bigint, status: bigint, deadline: bigint, ethTarget: bigint, multiplierX10: bigint, strikePrice: bigint, graduationMcap: bigint, graduationPrice: bigint, minLiquidity: bigint, cumulativeAtStart: bigint, timestampAtStart: bigint, winningBucket: bigint, description: string, outcome: boolean, resolutionTime: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'noPool'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'noStakes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingWinnings'): TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'protocolTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rangePool'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rangeStakes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveCustom'): TypedContractMethod<
      [marketId: BigNumberish, outcome: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveGradMarkets'): TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveRange'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [marketId: BigNumberish, side: boolean, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'stakeRange'): TypedContractMethod<
      [marketId: BigNumberish, bucket: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'tokenMarkets'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'yesPool'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'yesStakes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'MarketCancelled'): TypedContractEvent<MarketCancelledEvent.InputTuple, MarketCancelledEvent.OutputTuple, MarketCancelledEvent.OutputObject>;
getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'StakePlaced'): TypedContractEvent<StakePlacedEvent.InputTuple, StakePlacedEvent.OutputTuple, StakePlacedEvent.OutputObject>;
getEvent(key: 'WinningsClaimed'): TypedContractEvent<WinningsClaimedEvent.InputTuple, WinningsClaimedEvent.OutputTuple, WinningsClaimedEvent.OutputObject>;

    filters: {
      
      'MarketCancelled(uint256)': TypedContractEvent<MarketCancelledEvent.InputTuple, MarketCancelledEvent.OutputTuple, MarketCancelledEvent.OutputObject>;
      MarketCancelled: TypedContractEvent<MarketCancelledEvent.InputTuple, MarketCancelledEvent.OutputTuple, MarketCancelledEvent.OutputObject>;
    

      'MarketCreated(uint256,address,uint8,uint256)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'MarketResolved(uint256,bool,uint8)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'StakePlaced(uint256,address,uint8,uint256,uint256)': TypedContractEvent<StakePlacedEvent.InputTuple, StakePlacedEvent.OutputTuple, StakePlacedEvent.OutputObject>;
      StakePlaced: TypedContractEvent<StakePlacedEvent.InputTuple, StakePlacedEvent.OutputTuple, StakePlacedEvent.OutputObject>;
    

      'WinningsClaimed(uint256,address,uint256)': TypedContractEvent<WinningsClaimedEvent.InputTuple, WinningsClaimedEvent.OutputTuple, WinningsClaimedEvent.OutputObject>;
      WinningsClaimed: TypedContractEvent<WinningsClaimedEvent.InputTuple, WinningsClaimedEvent.OutputTuple, WinningsClaimedEvent.OutputObject>;
    
    };
  }