/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBondingCurveV2, IBondingCurveV2Interface } from "../../../launchpad/TokenFactory.sol/IBondingCurveV2.js";

  const _abi = [
  {
    "inputs": [],
    "name": "currentPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IBondingCurveV2__factory {
    static readonly abi = _abi;
    static createInterface(): IBondingCurveV2Interface {
      return new Interface(_abi) as IBondingCurveV2Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBondingCurveV2 {
      return new Contract(address, _abi, runner) as unknown as IBondingCurveV2;
    }
  }
  