/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IUniswapV2Factory, IUniswapV2FactoryInterface } from "../../../dex/UniswapV2Router.sol/IUniswapV2Factory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "createPair",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "getPair",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IUniswapV2Factory__factory {
    static readonly abi = _abi;
    static createInterface(): IUniswapV2FactoryInterface {
      return new Interface(_abi) as IUniswapV2FactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IUniswapV2Factory {
      return new Contract(address, _abi, runner) as unknown as IUniswapV2Factory;
    }
  }
  